project_id = "bywadbngfzeeroeayxmf"

[functions.ai-chat]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.generate-flashcards]
verify_jwt = false

[functions.generate-notes]
verify_jwt = false
